services:
  database:
    image: postgres
    container_name: trackit-database
    ports:
      - 5432:5432
    volumes:
      - ./docker/trackit:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
