services:
  trackit-database:
    image: postgres
    container_name: trackit-database
    networks:
      - trackit-network
    ports:
      - 5432:5432
    volumes:
      - ./Docker/Volumes/trackit-database:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
          
networks:
  trackit-network:
    driver: bridge